### PR TITLE
📨  Add medium and tall mixins

### LINKED ISSUE #45: Add mixin to style tall, medium-tall toolbars
Moved from https://github.com/PolymerElements/paper-tooltip/issues/18#issuecomment-145674155 cc @notwaldorf

### PR DESCRIPTION
**Pull request by samccone**
Fixes #45 

👀 **R:**  @notwaldorf @blasten

---

:goat: :star: :gb:

### CODE REVIEW

**Comment by blasten** [comment]
@samccone sorry for the late response. Can you rebase your branch?

**Comment by samccone** [comment]
@blasten updated and I dropped the readme change since the robot will do the work now

**Comment by blasten** [comment]
@samccone would you mind if you update the code snippets to include the language so they can be highlighted?  e.g. https://github.com/PolymerElements/paper-scroll-header-panel/blob/master/paper-scroll-header-panel.html#L27

**Comment by samccone** [comment]
not sure I follow @blasten 

also can we open another PR to resolve that since it is unrelated to this fix

**Comment by blasten** [comment]
Ok that's fine

**Pull request merged**
