### PR TITLE
Fixes #77: Change text color to `--dark-theme-text-color`.

### LINKED ISSUE #77: colors :)
dear polymer, the last commit has changed how  `primary-text-color` and`text-primary-color` work, effectively making `text-primary-color` deprecated except all other elements still use it for text and icons
will there be a update really soon to all elements to make the switch?
is there any way to have other elements that used `primary-text-color` for dark colors/fonts use `text-primary-color`? 
here is my current theme
`<--dark-primary-color: #1976D2;
    --default-primary-color: #2196F3;
    --light-primary-color: #BBDEFB;
    --primary-text-color: #ffffff; /*text/icons*/
    --accent-color: #FF5252;
    --primary-background-color: #BBDEFB;
    --text-primary-color: #212121;
    --secondary-text-color: #727272;
    --disabled-text-color: #bdbdbd;
    --divider-color: #B6B6B6;>`
in the attached image, the black circled content uses `primary-text-color` whereas the green uses 
`text-primary-color`
untitled

### PR DESCRIPTION
**Pull request by bicknellr**
(Fixes #77.)

### CODE REVIEW

**Comment by abdonrd** [comment]
Back to deprecated value? https://github.com/PolymerElements/paper-styles/blob/master/default-theme.html#L61-L65

**Comment by chuckh** [comment]
Maybe a new name should be created such as `--toolbar-primary-color` instead of `--text-primary-color`

**Comment by bicknellr** [comment]
Thanks both for pointing out that this is a little weird. After talking with @notwaldorf and checking the spec, it seems that the `--light-theme...` and `--dark-theme...` CSS variables in the default theme import aren't meant to be mutually exclusive as I had originally thought. Instead they're meant to be used in light-background and dark-background situations - which may be on the same page. So, I switched this to `--dark-theme-text-color`.

**Comment by notwaldorf** [comment]
Hurray! LGTM!

**Comment by bicknellr** [comment]
(Last push was just to change the commit message.)

**Comment by chuckh** [comment]
LGTM2!

**Comment by abdonrd** [comment]
LGTM too! :smiley:

**Comment by bicknellr** [comment]
https://github.com/PolymerElements/paper-toolbar/pull/80/files#diff-c039fb2eac608d42d39d9165a1afba13R87 grrr docs.

**Comment by bicknellr** [comment]
#81

**Pull request merged**
